# Site settings
title: "邝炜瑞, Weirui Kuang's Homepage"
description: "Learner."

# Project name
user_name: "weiruikuang"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "邝炜瑞, Weirui Kuang"
resume_title:                   "Senior Machine Learning Engineer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "weiruikuang@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "0"
resume_contact_address:         "Hangzhou"

resume_header_contact_info:     "E-mail: weiruikuang@gmail.com"
orgnization:                    "@ALIBABA GROUP @DAMO ACADEMY"
display_header_contact_info:    "true"

resume_header_intro: "<p>Welcome to my homepage! Feel free to contact me at any time.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
# resume_looking_for_work:        "no"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_publications:    true
resume_section_news:            true
# resume_section_projects:        true
# resume_section_skills:          true
# resume_section_recognition:     true
resume_section_links:           true
# resume_section_associations:    true
# resume_section_interests:       true
# resume_section_blogs:           true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/rayrayraykk"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  # resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://weiruikuang.com/"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

plugins:
  - jekyll-seo-tag

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
